#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# For increasing in the number of projects. It makes getting back to the project root easier: cd $PROJECT_ROOT
PROJECT_ROOT=$(pwd)

cd $PROJECT_ROOT/portfolio_gallery/backend

yarn prettier

yarn lint

yarn test -ci
